sudo: false
language: python

cache: pip

matrix:
  include:
    - python: 3.5
      env: TOXENV=py,codecov
    - python: 3.6
      env: TOXENV=py,codecov
    - python: 3.6
      env: TOXENV=lint
    - python: 3.6
      env: TOXENV=docs

install:
  - pip install tox
  - git config --global user.email "test@travis.org"
  - git config --global user.name "Travis Runner"

script: tox
